[package]
name = "smash-gamepad-overlay"
version = "0.1.0"
authors = []
edition = "2021"

[package.metadata.skyline]
titleid = "01006A800016E000" # Super Smash Bros. Ultimate

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = "0.6.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
