use crate::input::ControlId;

#[derive(Debug, Copy, Clone)]
pub(crate) struct SkinElement {
    pub control_id: ControlId,
    pub pane_name: &'static [u8],
    pub base_x: f32,
    pub base_y: f32,
    pub size_x: f32,
    pub size_y: f32,
    pub released_alpha: u8,
    pub pressed_alpha: u8,
    pub released_visible: bool,
    pub pressed_visible: bool,
    pub stick_movement_radius: Option<f32>,
}

#[derive(Debug, Copy, Clone)]
pub(crate) struct BuiltInSkin {
    pub name: &'static str,
    pub elements: &'static [SkinElement],
}

pub(crate) const MINIMAL_GAMECUBE_SKIN: BuiltInSkin = BuiltInSkin {
    name: "minimal_gamecube",
    elements: &MINIMAL_GAMECUBE_ELEMENTS,
};

const MINIMAL_GAMECUBE_ELEMENTS: [SkinElement; 22] = [
    SkinElement {
        control_id: ControlId::LeftStickGate,
        pane_name: b"sgpo_ls_gate\0",
        base_x: 8.0,
        base_y: -34.0,
        size_x: 48.0,
        size_y: 48.0,
        released_alpha: 128,
        pressed_alpha: 128,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::LeftStickDot,
        pane_name: b"sgpo_ls_dot\0",
        base_x: 32.0,
        base_y: -10.0,
        size_x: 10.0,
        size_y: 10.0,
        released_alpha: 180,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: Some(19.0),
    },
    SkinElement {
        control_id: ControlId::RightStickGate,
        pane_name: b"sgpo_rs_gate\0",
        base_x: 102.0,
        base_y: -100.0,
        size_x: 48.0,
        size_y: 48.0,
        released_alpha: 128,
        pressed_alpha: 128,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::RightStickDot,
        pane_name: b"sgpo_rs_dot\0",
        base_x: 126.0,
        base_y: -76.0,
        size_x: 10.0,
        size_y: 10.0,
        released_alpha: 180,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: Some(19.0),
    },
    SkinElement {
        control_id: ControlId::A,
        pane_name: b"sgpo_btn_a\0",
        base_x: 190.0,
        base_y: -34.0,
        size_x: 22.0,
        size_y: 22.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::B,
        pane_name: b"sgpo_btn_b\0",
        base_x: 162.0,
        base_y: -60.0,
        size_x: 22.0,
        size_y: 22.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::X,
        pane_name: b"sgpo_btn_x\0",
        base_x: 162.0,
        base_y: -8.0,
        size_x: 22.0,
        size_y: 22.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::Y,
        pane_name: b"sgpo_btn_y\0",
        base_x: 134.0,
        base_y: -34.0,
        size_x: 22.0,
        size_y: 22.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::L,
        pane_name: b"sgpo_btn_l\0",
        base_x: 0.0,
        base_y: 28.0,
        size_x: 42.0,
        size_y: 16.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::R,
        pane_name: b"sgpo_btn_r\0",
        base_x: 62.0,
        base_y: 28.0,
        size_x: 42.0,
        size_y: 16.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::ZL,
        pane_name: b"sgpo_btn_zl\0",
        base_x: 124.0,
        base_y: 28.0,
        size_x: 42.0,
        size_y: 16.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::ZR,
        pane_name: b"sgpo_btn_zr\0",
        base_x: 194.0,
        base_y: 28.0,
        size_x: 42.0,
        size_y: 16.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::L3,
        pane_name: b"sgpo_btn_l3\0",
        base_x: 30.0,
        base_y: -78.0,
        size_x: 28.0,
        size_y: 16.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::R3,
        pane_name: b"sgpo_btn_r3\0",
        base_x: 170.0,
        base_y: -78.0,
        size_x: 28.0,
        size_y: 16.0,
        released_alpha: 96,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::Plus,
        pane_name: b"sgpo_btn_plus\0",
        base_x: 116.0,
        base_y: -14.0,
        size_x: 18.0,
        size_y: 18.0,
        released_alpha: 80,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::Minus,
        pane_name: b"sgpo_btn_minus\0",
        base_x: 78.0,
        base_y: -14.0,
        size_x: 18.0,
        size_y: 18.0,
        released_alpha: 80,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::DpadUp,
        pane_name: b"sgpo_dpad_up\0",
        base_x: 76.0,
        base_y: -54.0,
        size_x: 16.0,
        size_y: 16.0,
        released_alpha: 80,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::DpadDown,
        pane_name: b"sgpo_dpad_down\0",
        base_x: 76.0,
        base_y: -86.0,
        size_x: 16.0,
        size_y: 16.0,
        released_alpha: 80,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::DpadLeft,
        pane_name: b"sgpo_dpad_left\0",
        base_x: 60.0,
        base_y: -70.0,
        size_x: 16.0,
        size_y: 16.0,
        released_alpha: 80,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::DpadRight,
        pane_name: b"sgpo_dpad_right\0",
        base_x: 92.0,
        base_y: -70.0,
        size_x: 16.0,
        size_y: 16.0,
        released_alpha: 80,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::GcLTrigger,
        pane_name: b"sgpo_gc_l\0",
        base_x: 0.0,
        base_y: 48.0,
        size_x: 48.0,
        size_y: 12.0,
        released_alpha: 80,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
    SkinElement {
        control_id: ControlId::GcRTrigger,
        pane_name: b"sgpo_gc_r\0",
        base_x: 188.0,
        base_y: 48.0,
        size_x: 48.0,
        size_y: 12.0,
        released_alpha: 80,
        pressed_alpha: 255,
        released_visible: true,
        pressed_visible: true,
        stick_movement_radius: None,
    },
];
